---
title: "Group2_HW1_Submision_Brooke-Sean-Faizaan"
output:
  html_document:
    df_print: paged
date: "2025-08-29"
editor_options:
  markdown:
    wrap: 72
---

```{r}
knitr::opts_chunk$set(echo = TRUE)


install.packages("ISLR") 
install.packages("patchwork")
library(patchwork)
library(ISLR) 
dim(College) # rows, cols
help(College)

vStore <- matrix(0,18,1000) 

for(i in 1:10000)
{ 
  vStore[,i]=sample(Wage$wage,1000,replace=TRUE) 
}

# storeIntVar <- table$GetDataInTable


apps<-College$Apps
apps


# we run sampling distros based on loads of different seeds. 
# Each time we random this, we will get different sampling data. 
# working hard to then run the code multiple times to see the difference in
# variation 

# -- This is the old way -- 
set.seed(1337)

# setting up an empty var for use later. Delegates 
bootsApplications<-NULL

# writing as dplyr
library(dplyr)
for(j in 1:1000)
{
  # in this case, the '.' is specifically piping "Apps" into those positions. 
  # so we're sampling (apps, len(apps), replacement = true)
  # why we don't use mean(.) here is because mean already
  # expects our sample from apps. So mean(.) and mean() are identical
  my_samp=apps%>%sample(.,length(.),replace=TRUE)%>%mean()
  # Once we grab a single sample 
  bootsApplications<-c(bootsApplications,my_samp)
  print(bootsApplications)
}

hist(bootsApplications)
quantile(bootsApplications,c(.1,.9))
``` 

## Solution 2 

```{r}
startTime <- Sys.time()
boots1 <- NULL
boots2 <- NULL
boots3 <- NULL

seeds <- sample(1:5000,3) 

set.seed(seeds[1])
for(j in 1:1000)
{
  my_samp=apps%>%sample(.,length(.),replace=TRUE)%>%mean()
  boots1<-c(boots1,my_samp)
}
#print(boots1)

set.seed(seeds[2])
for(j in 1:1000)
{
  my_samp=apps%>%sample(.,length(.),replace=TRUE)%>%mean()
  boots2<-c(boots2,my_samp)
}
#print(boots2)

set.seed(seeds[3])
for(j in 1:1000)
{
  my_samp=apps%>%sample(.,length(.),replace=TRUE)%>%mean()
  boots3<-c(boots3,my_samp)
}
#print(boots3)


##
##  Solution
##      2
##


df <- data.frame(boots1,boots2,boots3)
print(df)

boots4 <- NULL
boots5 <- NULL
boots6 <- NULL
set.seed(seeds[1])
for(j in 1:5000)
{
  my_samp=apps%>%sample(.,length(.),replace=TRUE)%>%mean()
  boots4<-c(boots4,my_samp)
}
#print(boots4)

set.seed(seeds[2])
for(j in 1:5000)
{
  my_samp=apps%>%sample(.,length(.),replace=TRUE)%>%mean()
  boots5<-c(boots5,my_samp)
}
#print(boots5)

set.seed(seeds[3])
for(j in 1:5000)
{
  my_samp=apps%>%sample(.,length(.),replace=TRUE)%>%mean()
  boots6<-c(boots6,my_samp)
}
#print(boots6)

df <- data.frame(boots4,boots5,boots6)
print(df)
endTime <- Sys.time()
elapsed <- endTime - startTime
print(paste("Main Calc Code: Time Elapsed - ",elapsed))
traceback()
```
```{r}
library(ggplot2)
library(patchwork)
startTime <- Sys.time()
quantile(boots1,.1,.9)
quantile(boots4,.1,.9)

p1 <- ggplot(data.frame(one_thousand_sample = boots1), aes(x = one_thousand_sample)) +
  geom_histogram(bins = 30, fill = "blue", alpha = 0.25) +
  labs(title = "Histogram of 1,000 samples")

# Make graph 2~ 5,000 samples 
p2 <- ggplot(data.frame(five_thousand_sample = boots4), aes(x = five_thousand_sample)) +
  geom_histogram(bins = 30, position = "identity", fill = "red", alpha = 0.25) +
  labs(title = "Histogram of 5,000 samples")

# Combine both hists with patchwork
p1 + p2
endTime <- Sys.time()
elapsed <- endTime - startTime
print(paste("Graphing Code: Time Elapsed - ", elapsed))
```
